---
plugin: aws_ec2

aws_access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY') }}"
aws_secret_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_SECRET_KEY') }}"

regions:
  - us-east-1

keyed_groups:
  - key: tags
    prefix: tag

  - prefix: instance_type
    key: instance_type

  - key: placement.region
    prefix: aws_region
