---
name: Molecule Test
on:
  push:
    tags:
      - release-v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
          
      - name: Molecule
        uses: gofrolist/molecule-action@v2.3.16
        with:
          molecule_command: test
          molecule_args: -d docker
          molecule_working_dir: alexanderNWO/dynamic-inventory-aws/my_new_role
        env:
          ANSIBLE_FORCE_COLOR: '1'
